# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad115b8ad7429ea852ca16bac24966fc197262878ffc7ede860f06ba2855c448ba581abb33485169e0f06f5082993dd5a456e40c66404a3b407f7ff8377c73b3

test:
  secret_key_base: 0cd94e5f9828ed9197f26ffb477bfc4e395bee06e2c99e6279f372fb233bfaede1a7de696b43467ee52714f08f118982054ebab8d504d22a2f570382bc399d73

# Do not keep production secrets in the repository,
# instead read values from the environment.

# This keybase is copied from the development one, Tyson said to do it :)
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: ad115b8ad7429ea852ca16bac24966fc197262878ffc7ede860f06ba2855c448ba581abb33485169e0f06f5082993dd5a456e40c66404a3b407f7ff8377c73b3

#  commented out like tyson said, this one is the original secret_key_base
