# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86fb1539373ca7c3838cbb291188b5358e37d514491742864bd65de7aada3b94fa2a0b349469fc15d93924c02639f8dbda67f8932082dc3cefebbc81d089003c

test:
  secret_key_base: f6ef25a50438c7cb353a83cc3ab975a5ba5ac7ba292e0f55138893e923dea2a52df2230872c646a46dad8a32ae42882452d3201c6eea927a4bdd4c3b5289ac50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 86fb1539373ca7c3838cbb291188b5358e37d514491742864bd65de7aada3b94fa2a0b349469fc15d93924c02639f8dbda67f8932082dc3cefebbc81d089003c
